### ISSUE TITLE
support gTTS ? and error

### ISSUE THREAD

**Issue by becauseimnoob** [alexlaverty/ttsvibelounge#7]
Can you add this feature for those who don't want to use Amazon's paid police? https://pypi.org/project/gTTS/

also i am getting errors while trying to use the program 

test page : https://www.reddit.com/r/Turkey/comments/y8rhm1/sezgin_tanr%C4%B1kulunun_tweeti/

```
2022-10-20 23:24:02 INFO     Current Clip Text :
--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\xsd\AppData\Local\Programs\Python\Python310\lib\logging\__init__.py", line 1103, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\xsd\AppData\Local\Programs\Python\Python310\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0131' in position 118: character maps to <undefined>
```
```

2022-10-20 23:24:22 INFO     Video Clips :
2022-10-20 23:24:22 INFO     48
2022-10-20 23:24:22 INFO     comment_line     :
Traceback (most recent call last):
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 341, in ffmpeg_parse_infos
    match = re.findall("([0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9])", line)[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\xsd\Desktop\ttsvibelounge\app.py", line 92, in <module>
    process_submissions(submissions)
  File "C:\Users\xsd\Desktop\ttsvibelounge\app.py", line 28, in process_submissions
    process_submission(submission)
  File "C:\Users\xsd\Desktop\ttsvibelounge\app.py", line 53, in process_submission
    vid.create(video_directory=video.folder_path, post=submission)
  File "C:\Users\xsd\Desktop\ttsvibelounge\video.py", line 381, in create
    audioclip = AudioFileClip(audio_filepath)
  File "<decorator-gen-48>", line 2, in __init__
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\decorators.py", line 89, in wrapper
    return f(*new_a, **new_kw)
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\audio\io\AudioFileClip.py", line 75, in __init__
    self.reader = FFMPEG_AudioReader(
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\audio\io\readers.py", line 60, in __init__
    infos = ffmpeg_parse_infos(filename, decode_file=decode_file)
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py", line 344, in ffmpeg_parse_infos
    raise IOError(
OSError: MoviePy error: failed to read the duration of file videos\y8rhm1_Sezgin_Tanrıkulunun_tweeti\y8rhm1_it1on23_1.mp3.
Here are the file infos returned by ffmpeg:

ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with gcc 9.2.1 (GCC) 20200122
  configuration: --enable-gpl --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvidstab --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libxvid --enable-libaom --enable-libmfx --enable-amf --enable-ffnvcodec --enable-cuvid --enable-d3d11va --enable-nvenc --enable-nvdec --enable-dxva2 --enable-avisynth --enable-libopenmpt
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
[wav @ 000001f64d2d9a80] Cannot check for SPDIF
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'videos\y8rhm1_Sezgin_Tanrıkulunun_tweeti\y8rhm1_it1on23_1.mp3':
  Duration: N/A, bitrate: 256 kb/s
    Stream #0:0: Audio: pcm_s16le ([1][0][0][0] / 0x0001), 16000 Hz, mono, s16, 256 kb/s
At least one output file must be specified

Exception ignored in: <function FFMPEG_AudioReader.__del__ at 0x000002786918E440>
Traceback (most recent call last):
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\audio\io\readers.py", line 269, in __del__
    self.close()
  File "C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\audio\io\readers.py", line 260, in close
    if self.proc:
AttributeError: 'FFMPEG_AudioReader' object has no attribute 'proc'
```

**Comment by alexlaverty** [comment]
I have added gtts support for you in the latest master, I'll have a look into your other error, looks like it's because there is a special character little L in your title `Sezgin Tanrıkulu'nun tweeti`  that moviepy doesn't seem to like

**Comment by alexlaverty** [comment]
I believe I have fixed the special character errors you're getting by providing utf-8 encoding support to the logging :

https://github.com/alexlaverty/ttsvibelounge/commit/f1a54b66d8319b4ce0c197093e0c970758703553

I was able to generate a video based off the url you provided, let me know how you go.

**Comment by becauseimnoob** [comment]
thank you for your correction

```
cd assets/backgrounds
yt-dlp -f 22 --output "%(uploader)s_%(id)s.%(ext)s" https://www.youtube.com/playlist?list=PLGmxyVGSCDKvmLInHxJ9VdiwEb82Lxd2E
```
I downloaded the videos as you provided, is this an **error**?

```
2022-10-21 12:49:58 INFO     Video Clips :
2022-10-21 12:49:58 INFO     5
2022-10-21 12:49:58 INFO     Current Video Duration : 66.02
2022-10-21 12:49:58 INFO     Reached Maximum Video Length : 60
2022-10-21 12:49:58 INFO     Exiting...
2022-10-21 12:49:58 INFO     Video Clip Duration      : 66.02
2022-10-21 12:49:58 INFO     Background Clip Duration : 12.4
2022-10-21 12:49:58 INFO     Looping Background
2022-10-21 12:49:58 INFO     Looped Background Clip Duration : 66.02
2022-10-21 12:49:59 INFO     Looping Overlay
2022-10-21 12:49:59 INFO     Looped Overlay Clip Duration : 66.02
2022-10-21 12:49:59 INFO     Compiling video, this takes a while, please be patient : )
C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:154: UserWarning: In file assets\backgrounds\NO COPYRIGHT MOTION GRAPHICS_K8jUGKkbHpg.mp4, 2764800 bytes wanted but 0 bytes read,at frame index 371 (out of a total 371 frames), at time 12.38/12.40 sec. Using the last valid frame instead.
  warnings.warn(
C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:154: UserWarning: In file assets\backgrounds\NO COPYRIGHT MOTION GRAPHICS_K8jUGKkbHpg.mp4, 2764800 bytes wanted but 0 bytes read,at frame index 370 (out of a total 371 frames), at time 12.35/12.40 sec. Using the last valid frame instead.
  warnings.warn(
```

**Comment by alexlaverty** [comment]
Can you check there aren't any partially downloaded files in the backgrounds directory and make sure you can open and view all the downloaded videos correctly in a video player without error. Sounds like an issue with one of the video backgrounds that was downloaded.

**Comment by anhdodotnet** [comment]
gTTS error?
![image](https://user-images.githubusercontent.com/25850343/197192703-2c2dc94c-cab6-4781-a06b-f373e7672327.png)

**Comment by becauseimnoob** [comment]
> Can you check there aren't any partially downloaded files in the backgrounds directory and make sure you can open and view all the downloaded videos correctly in a video player without error. Sounds like an issue with one of the video backgrounds that was downloaded.
> 
> If you scroll up in your log output, it should tell you which video file it was attempting to use :
> 
> ```
> Randomly Selecting Background : 
> ```

There are more than 2000 videos from here and it takes up unnecessary space on our hard drive. Wouldn't it be better to create a background by taking sections from one long video instead?

https://github.com/elebumm/RedditVideoMakerBot/blob/master/video_creation/background.py

**Comment by alexlaverty** [comment]
Eek.. you don't have to download all of them, only as many as you want to get you started, was just providing that command as a suggestion on where to get video backgrounds from. You can also supply your own.

**Comment by becauseimnoob** [comment]
> Eek.. you don't have to download all of them, only as many as you want to get you started, was just providing that command as a suggestion on where to get video backgrounds from. You can also supply your own.
> 
> I have updated the README.md file to add a limit to the number of backgrounds that get downloaded via `--playlist-items` :
> 
> ```
> yt-dlp --playlist-items 1:10 -f 22 --output "%(uploader)s_%(id)s.%(ext)s" https://www.youtube.com/playlist?list=PLGmxyVGSCDKvmLInHxJ9VdiwEb82Lxd2E
> ```

I do as you say, but the above information is still displayed, when I look at the log file, I see this
```
2022-10-22 16:05:10 INFO     Compiling video, this takes a while, please be patient : )
C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:154: UserWarning: In file assets\backgrounds\NO COPYRIGHT MOTION GRAPHICS_4DTO4uHRKqQ.mp4, 2764800 bytes wanted but 0 bytes read,at frame index 308 (out of a total 308 frames), at time 10.28/10.29 sec. Using the last valid frame instead.
  warnings.warn(
C:\Users\xsd\Desktop\ttsvibelounge\venv\lib\site-packages\moviepy\video\io\ffmpeg_reader.py:154: UserWarning: In file assets\backgrounds\NO COPYRIGHT MOTION GRAPHICS_4DTO4uHRKqQ.mp4, 2764800 bytes wanted but 0 bytes read,at frame index 307 (out of a total 308 frames), at time 10.24/10.29 sec. Using the last valid frame instead.
  warnings.warn(
```

`2022-10-22 16:01:37 INFO     Randomly Selecting Background : NO COPYRIGHT MOTION GRAPHICS_4DTO4uHRKqQ.mp4`

if it's not a bug i can ignore it
